/* ================= 通用顶点着色器（世界空间光照） ================= */
var COMMON_VS=[
'varying vec3 vLocal; varying vec3 vNw; varying vec3 vView; varying vec3 vWorld;',
'varying vec3 vTw1; varying vec3 vTw2;',
'void main(){',
'  vLocal=normalize(position);',
'  vec4 wp=modelMatrix*vec4(position,1.0);',
'  vWorld=wp.xyz;',
'  mat3 nm=mat3(modelMatrix);',
'  vNw=normalize(nm*normal);',
'  vec3 lp=normalize(position);',
'  vec3 lt1=normalize(cross(lp, abs(lp.y)<0.98 ? vec3(0.0,1.0,0.0) : vec3(1.0,0.0,0.0)));',
'  vec3 lt2=normalize(cross(lp,lt1));',
'  vTw1=normalize(nm*lt1);',
'  vTw2=normalize(nm*lt2);',
'  vView=normalize(cameraPosition-wp.xyz);',
'  gl_Position=projectionMatrix*viewMatrix*wp;',
'}'
].join('\n');

/* ================= 岩质行星 ================= */
var ROCKY_FS=[
'varying vec3 vLocal; varying vec3 vNw; varying vec3 vView; varying vec3 vWorld;',
'varying vec3 vTw1; varying vec3 vTw2;',
'uniform float uTime;',
'uniform vec3 uSunDir; uniform vec3 uSunCol;',
'uniform vec3 uC0; uniform vec3 uC1; uniform vec3 uC2; uniform vec3 uC3;',
'uniform float uScale; uniform vec3 uSeed; uniform float uOcean; uniform float uSea;',
'uniform float uIce; uniform float uBump; uniform float uCrater; uniform float uAtmo;',
'float terrain(vec3 p){',
'  vec3 q=p*uScale+uSeed;',
'  float base=fbm(q,5);',
'  float rid=ridged(q*2.6,4);',
'  float h=base*0.80+rid*0.30;',
'  if(uCrater>0.001){ float cr=ridged(q*9.0,3); h+=(1.0-cr)*uCrater*0.22; }',
'  return h;',
'}',
'void main(){',
'  vec3 p=normalize(vLocal);',
'  vec3 t1=normalize(cross(p, abs(p.y)<0.98 ? vec3(0.0,1.0,0.0) : vec3(1.0,0.0,0.0)));',
'  vec3 t2=normalize(cross(p,t1));',
'  float e=0.012;',
'  float h=terrain(p);',
'  float hA=terrain(p+t1*e), hB=terrain(p-t1*e);',
'  float hC=terrain(p+t2*e), hD=terrain(p-t2*e);',
'  vec3 nrm=normalize(vNw-(vTw1*(hA-hB)+vTw2*(hC-hD))*uBump);',
'  float land=smoothstep(uSea-0.035,uSea+0.035,h);',
'  float ocean=uOcean*(1.0-land);',
'  float dh=clamp((h-(uSea-0.02))/max(0.001,(1.0-uSea+0.02)),0.0,1.0);',
'  vec3 alb=mix(uC0,uC1,smoothstep(0.0,0.18,dh));',
'  alb=mix(alb,uC2,smoothstep(0.20,0.55,dh));',
'  alb=mix(alb,uC3,smoothstep(0.58,0.92,dh));',
'  vec3 sea=mix(vec3(0.010,0.045,0.115),vec3(0.025,0.145,0.280),smoothstep(0.0,0.35,1.0-dh));',
'  alb=mix(alb,sea,ocean);',
'  float ipol=fbm(p*4.0+uSeed*2.0,3)*0.09;',
'  float ice=smoothstep(uIce-0.06,uIce+0.05,abs(p.y)+ipol);',
'  alb=mix(alb,vec3(0.95,0.97,1.0),ice*0.94);',
'  vec3 L=normalize(uSunDir);',
'  float ndl=dot(nrm,L);',
'  float term=clamp((ndl+0.22)/1.22,0.0,1.0);',
'  vec3 V=normalize(vView);',
'  vec3 Hv=normalize(L+V);',
'  float spec=pow(max(dot(nrm,Hv),0.0),120.0);',
'  float fres=pow(1.0-max(dot(nrm,V),0.0),3.0);',
'  vec3 col=alb*(term*1.35+0.020)*uSunCol;',
'  col+=uSunCol*spec*(1.0-land)*ocean*1.5;',
'  col+=uSunCol*fres*(1.0-land)*ocean*0.28;',
'  col+=uSunCol*term*ice*0.28;',
'  col+=uSunCol*fres*max(term,0.06)*uAtmo;',
'  gl_FragColor=vec4(toSRGB(aces(col)),1.0);',
'}'
].join('\n');
ROCKY_FS=NOISE_GLSL+'\n'+ROCKY_FS;

/* ================= 气态巨行星 ================= */
var GAS_FS=[
'varying vec3 vLocal; varying vec3 vNw; varying vec3 vView; varying vec3 vWorld;',
'varying vec3 vTw1; varying vec3 vTw2;',
'uniform float uTime;',
'uniform vec3 uSunDir; uniform vec3 uSunCol;',
'uniform vec3 uC0; uniform vec3 uC1; uniform vec3 uC2; uniform vec3 uC3;',
'uniform vec3 uSpotCol; uniform float uSpot; uniform float uBands; uniform vec3 uSeed;',
'uniform float uSwirl; uniform float uAtmo;',
'void main(){',
'  vec3 p=normalize(vLocal);',
'  float lat=clamp(p.y,-1.0,1.0);',
'  float t=uTime*0.008;',
'  float warp=fbm(vec3(p.x*1.6,lat*4.5+t,p.z*1.6)+uSeed,4)-0.5;',
'  float band=lat*uBands+warp*2.1*uSwirl;',
'  float turb=fbm(vec3(p.x*5.0,lat*4.0+t*2.0,p.z*5.0)+uSeed*3.0,4)-0.5;',
'  band+=turb*0.55;',
'  float s=sin(band*3.14159265);',
'  float s2=sin(band*6.28318530+1.1);',
'  vec3 alb=mix(uC0,uC1,smoothstep(-0.9,0.9,s));',
'  alb=mix(alb,uC2,smoothstep(0.15,0.95,s2)*0.85);',
'  alb=mix(alb,uC3,smoothstep(0.72,1.0,turb*0.5+0.5)*0.5);',
'  float streak=fbm(vec3(p.x*9.0,lat*30.0,p.z*9.0),3);',
'  alb*=0.92+streak*0.16;',
'  if(uSpot>0.001){',
'    vec3 sd=normalize(vec3(0.62,-0.20,0.76));',
'    float dd=distance(p,sd);',
'    float ov=smoothstep(0.32,0.10,dd);',
'    float sw=fbm(p*7.0+vec3(t*3.0,0.0,0.0),3);',
'    alb=mix(alb,uSpotCol,ov*uSpot*(0.7+sw*0.5));',
'  }',
'  vec3 nrm=normalize(vNw);',
'  vec3 L=normalize(uSunDir);',
'  float term=clamp((dot(nrm,L)+0.25)/1.25,0.0,1.0);',
'  vec3 V=normalize(vView);',
'  float fres=pow(1.0-max(dot(nrm,V),0.0),3.0);',
'  vec3 col=alb*(term*1.30+0.022)*uSunCol;',
'  col+=uSunCol*fres*max(term,0.05)*uAtmo;',
'  gl_FragColor=vec4(toSRGB(aces(col)),1.0);',
'}'
].join('\n');
GAS_FS=NOISE_GLSL+'\n'+GAS_FS;
/* ANCHOR_B2B_END */
